spin_manifest_version = 2

[application]
name = "gateway"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "api-gateway"

[component.api-gateway]
source = "api-gateway/target/wasm32-wasip1/release/api_gateway.wasm"
allowed_outbound_hosts = [
	"https://accounts.google.com",
	"https://www.googleapis.com",
	"https://oauth2.googleapis.com",
	"https://openidconnect.googleapis.com",
]
key_value_stores = ["default"]

[component.api-gateway.build]
command = "cargo build -p api-gateway --target wasm32-wasip1 --release"
