
spin_manifest_version = 2

[application]
name = "rate-limiter-service"
version = "0.1.0"
authors = ["Albergue Del Carrascalejo"]

[variables]
rate_limit_requests = { default = "10" }
rate_limit_window = { default = "60" }
log_level = { default = "debug" }

[[trigger.http]]
route = "/api/*"
component = "rate-limiter-service"

[component.rate-limiter-service]
source = "target/wasm32-wasip1/release/rate_limiter_service.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]

[component.rate-limiter-service.build]
command = "cargo build --target wasm32-wasip1 --release"

[component.rate-limiter-service.variables]
rate_limit_requests = "{{ rate_limit_requests }}"
rate_limit_window = "{{ rate_limit_window }}"
log_level = "{{ log_level }}"
