
spin_manifest_version = 2

[application]
name = "booking-service"
version = "0.1.0"
authors = ["Albergue Del Carrascalejo"]

[variables]
database_url = { required = true }
neon_database_url = { required = true }
booking_timeout_hours = { default = "2" }
log_level = { default = "info" }

[[trigger.http]]
route = "/api/*"
component = "booking-service"

[component.booking-service]
source = "target/wasm32-wasip1/release/booking_service.wasm"
allowed_outbound_hosts = ["https://*.neon.tech", "https://*.postgres.com", "http://mqtt-broker-service.spin.internal"]
key_value_stores = ["default"]
sqlite_databases = ["default"]

[component.booking-service.build]
command = "cargo build --target wasm32-wasip1 --release"

[component.booking-service.variables]
database_url = "{{ database_url }}"
neon_database_url = "{{ neon_database_url }}"
booking_timeout_hours = "{{ booking_timeout_hours }}"
log_level = "{{ log_level }}"
