[package]
name = "albergue-migration"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
sea-orm-migration.workspace = true
tokio.workspace = true

[[bin]]
name = "albergue-migration"
path = "src/main.rs"
